---
title: "Untitled"
output:
  html_document:
    toc: true
    toc_depth: 3
params:
  dir_proj: ""
  settings_to_print: NULL
---

```{css, echo=FALSE}
# to make sure tables don't wrap
body .main-container {
  max-width: 2560px !important;
  width: 1280px !important;
}
body {
  max-width: 2560px !important;
}
```

```{r , include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r , results = "asis"}
if (!is.null(params$settings_to_print)) {
  if("path_proj" %in% colnames(params$settings_to_print)) {
    cat("\n")
    cat("path")
    cat("\n")
    cat(params$settings_to_print$path_proj)
    cat("\n")
    }
  pander::pandoc.table(
    params$settings_to_print[, -which(colnames(params$settings_to_print) %in% c(
      "path_proj",
      "iter",
      "p_dots",
      "fn"
    ))]
  )
}
```

```{r , results = 'asis'}
dir_base_vec <- c("exp", "val", "extr", "disp")
short_to_full_dir_base <- c("exp" = "Exploration",
                            "val" = "Validation",
                            "extr" = "Results: tables",
                            "disp" = "Results: plots")
for(dir_base in dir_base_vec){
  dir_curr <- file.path(params$dir_proj, dir_base)
  pander::pandoc.header(short_to_full_dir_base[dir_base])
  format <- ifelse(
    knitr::is_html_output(),
    "png",
    "pdf")
  pipeline::print_plots_in_dir(dir_curr, format = format)
  if(dir_base == "val"){
    # make comments
    # add references
  }
  pipeline::print_tbl_in_dir(dir_curr)
}

```

```{r , results = "asis"}
path_mod <- file.path(params$dir_proj, "fit", "mod_list.rds")
if (file.exists(path_mod)) {
  pander::pandoc.header("Raw model output", level = 1)
}
```

```{r , results = "asis"}
path_mod <- file.path(params$dir_proj, "fit", "mod_list.rds")
if (file.exists(path_mod)) {
  pander::pandoc.header("Short summary", level = 2)
}
```

```{r }
if (file.exists(path_mod)) {
  fit_obj <- try(readRDS(path_mod), silent = TRUE)
  try(fit_obj$full, silent = TRUE)
}
```

```{r , results = "asis"}
path_mod <- file.path(params$dir_proj, "fit", "mod_list.rds")
if (file.exists(path_mod)) {
  pander::pandoc.header("Long summary", level = 2)
}
```

```{r }
if (file.exists(path_mod)) {
  try(summary(fit_obj$full), silent = TRUE)
}
```
